# Generated by Django 3.2.4 on 2021-06-05 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('profiles', '0003_remove_profile_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='neighborhood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='locations.neighborhood'),
            preserve_default=False,
        ),
    ]
