# Generated by Django 3.2.4 on 2021-06-05 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_rename_neighborhood_contact_neighborhood'),
        ('profiles', '0004_profile_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='locations.neighborhood'),
        ),
    ]
