# Generated by Django 3.2.4 on 2021-06-04 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210604_1911'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
