# Generated by Django 3.2.4 on 2021-06-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_category_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='category',
            field=models.CharField(choices=[('Police', 'Police'), ('Health', 'Health')], max_length=6),
        ),
    ]
