# Generated by Django 3.2.4 on 2021-06-05 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_contact_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Neighborhood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='locations.neighborhood'),
            preserve_default=False,
        ),
    ]
