# Generated by Django 3.2.4 on 2021-06-05 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_contact_neighborhood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Neighborhood',
            new_name='neighborhood',
        ),
    ]
