# Generated by Django 3.2.4 on 2021-06-06 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20210606_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='admin',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='locations.admin'),
            preserve_default=False,
        ),
    ]
