# Generated by Django 3.2.4 on 2021-06-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_neighborhood_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
